# Generated by Django 4.2.9 on 2025-11-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emocionreal',
            name='porcentaje',
            field=models.FloatField(default=0.0, help_text='Promedio de probabilidad según la cámara'),
        ),
    ]
