# Generated by Django 4.2.9 on 2025-11-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_emocionreal_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='como_realizarla',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='importancia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='recurso',
            field=models.TextField(blank=True, null=True),
        ),
    ]
