# Generated by Django 4.2.9 on 2025-11-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_actividad_como_realizarla_actividad_importancia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilidad', models.BooleanField()),
                ('recomendaria', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
