# Generated by Django 4.2.9 on 2025-11-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_encuestasatisfaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestasatisfaccion',
            name='recomendaria',
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='recomendacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='encuestasatisfaccion',
            name='utilidad',
            field=models.CharField(choices=[('yes', 'Sí'), ('no', 'No')], max_length=3),
        ),
    ]
