# Generated by Django 4.2.9 on 2025-11-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_encuestasatisfaccion_recomendaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestasatisfaccion',
            name='utilidad',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')]),
        ),
    ]
