# Generated by Django 4.2.9 on 2025-11-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_encuestasatisfaccion_utilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestasatisfaccion',
            name='utilidad',
            field=models.IntegerField(),
        ),
    ]
