# Generated by Django 4.2.9 on 2025-11-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_encuestasatisfaccion_utilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
