# Generated by Django 4.2.9 on 2025-11-13 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_sesion_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='sesion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='gestion.sesion'),
        ),
        migrations.AlterField(
            model_name='encuestasatisfaccion',
            name='recomendacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='encuestasatisfaccion',
            name='utilidad',
            field=models.CharField(max_length=50),
        ),
    ]
